import {
  dialogView,
  fertilizerType,
  fieldMode,
  stageFocusType,
  toolLevel,
  toolType,
} from '../enums.js'

export const shapeOf = object =>
  Object.keys(object).reduce((acc, key) => {
    acc[key] = typeof object[key]
    return acc
  }, {})

export const testCrop = (item = {}) => ({
  daysOld: 0,
  daysWatered: 0,
  fertilizerType: fertilizerType.NONE,
  itemId: 'sample-item-1',
  wasWateredToday: false,
  ...item,
})

/**
 * @param {Omit<farmhand.shoveledPlot, 'isShoveled' | 'daysUntilClear'>} plotProps
 */
export const testShoveledPlot = plotProps => ({
  isShoveled: true,
  daysUntilClear: 5,
  ...plotProps,
})

export const testItem = (item = {}) => ({
  id: '',
  name: '',
  type: /** @type {farmhand.itemType} */ ('CRAFTED_ITEM'),
  value: 0,
  description: '',
  doesPriceFluctuate: false,
  isReplantable: false,
  ...item,
})

/**
 * Creates a minimal but complete farmhand.state object for testing
 * @param {Partial<farmhand.state>} overrides - Properties to override in the test state
 * @returns {farmhand.state}
 */
export const testState = (overrides = {}) => ({
  activePlayers: null,
  allowCustomPeerCowNames: false,
  cellarInventory: [],
  currentDialogView: dialogView.NONE,
  completedAchievements: {},
  cowForSale: {
    baseWeight: 1000,
    color: 'BROWN',
    colorsInBloodline: { BROWN: true },
    daysOld: 1,
    daysSinceMilking: 0,
    daysSinceProducingFertilizer: 0,
    gender: 'FEMALE',
    happiness: 0.5,
    happinessBoostsToday: 0,
    id: 'test-cow',
    isBred: false,
    isUsingHuggingMachine: false,
    name: 'Test Cow',
    originalOwnerId: 'test-owner',
    ownerId: 'test-owner',
    timesTraded: 0,
    weightMultiplier: 1,
  },
  cowBreedingPen: {
    cowId1: null,
    cowId2: null,
    daysUntilBirth: -1,
  },
  cowColorsPurchased: {},
  cowIdOfferedForTrade: '',
  cowInventory: [],
  cowsSold: {},
  cowsTraded: 0,
  cowTradeTimeoutId: null,
  cropsHarvested: {},
  dayCount: 0,
  experience: 0,
  farmName: 'Test Farm',
  field: [[]],
  fieldMode: fieldMode.OBSERVE,
  forest: [[]],
  getCowAccept: null,
  getCowReject: null,
  getCowTradeRequest: null,
  getPeerMetadata: null,
  hasBooted: false,
  heartbeatTimeoutId: null,
  historicalDailyLosses: [],
  historicalDailyRevenue: [],
  historicalValueAdjustments: [],
  hoveredPlotRangeSize: 0,
  id: 'test-id',
  inventory: [],
  inventoryLimit: 50,
  isAwaitingCowTradeRequest: false,
  isAwaitingNetworkRequest: false,
  isCombineEnabled: false,
  isMenuOpen: false,
  itemsSold: {},
  cellarItemsSold: {},
  isChatOpen: false,
  isDialogViewOpen: false,
  isOnline: false,
  isWaitingForDayToCompleteIncrementing: false,
  learnedRecipes: {},
  loanBalance: 0,
  loansTakenOut: 0,
  money: 500,
  latestNotification: null,
  newDayNotifications: [],
  notificationLog: [],
  peers: {},
  peerRoom: null,
  pendingPeerMessages: [],
  latestPeerMessages: [],
  sendPeerMetadata: null,
  selectedCowId: '',
  selectedItemId: '',
  priceCrashes: {},
  priceSurges: {},
  profitabilityStreak: 0,
  record7dayProfitAverage: 0,
  recordProfitabilityStreak: 0,
  recordSingleDayProfit: 0,
  revenue: 0,
  redirect: '',
  room: 'test-room',
  sendCowAccept: null,
  sendCowReject: null,
  purchasedCombine: 0,
  purchasedComposter: 0,
  purchasedCowPen: 0,
  purchasedCellar: 0,
  purchasedField: 0,
  purchasedForest: 0,
  purchasedSmelter: 0,
  sendCowTradeRequest: null,
  showHomeScreen: true,
  showNotifications: true,
  stageFocus: stageFocusType.HOME,
  todaysNotifications: [],
  todaysLosses: 0,
  todaysPurchases: {},
  todaysRevenue: 0,
  todaysStartingInventory: {},
  toolLevels: {
    [toolType.HOE]: toolLevel.DEFAULT,
    [toolType.SCYTHE]: toolLevel.DEFAULT,
    [toolType.SHOVEL]: toolLevel.UNAVAILABLE,
    [toolType.WATERING_CAN]: toolLevel.DEFAULT,
  },
  useAlternateEndDayButtonPosition: false,
  valueAdjustments: {},
  version: '1.0.0',
  ...overrides,
})
