name: CI

on:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  lint_test_type:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Reconfigure git to use HTTP authentication
        run: >
          git config --global url."https://github.com/".insteadOf ssh://git@github.com/
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: 'Install dependencies'
        run: npm ci

      - name: 'Install E2E dependencies'
        run: cd e2e && npm ci

      - name: 'Lint code'
        run: npm run lint

      - name: 'Run unit tests'
        run: npm test -- --coverage

      - name: 'Check types'
        run: npm run check:types

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: 'Install dependencies'
        run: npm ci

      - name: 'Build web app artifacts'
        run: |
          npm run build

      - uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: dist

  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Reconfigure git to use HTTP authentication
        run: >
          git config --global url."https://github.com/".insteadOf ssh://git@github.com/

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Install E2E dependencies and browsers
        run: |
          cd e2e
          npm ci
          npx playwright install --with-deps

      - name: Start backend Redis services
        run: docker compose up -d

      - name: Run E2E tests
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: npm run e2e
