name: CI

on:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  lint_test_type:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Reconfigure git to use HTTP authentication
        run: >
          git config --global url."https://github.com/".insteadOf ssh://git@github.com/
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: 'Install dependencies'
        run: npm ci

      - name: 'Lint code'
        run: npm run lint

      - name: 'Run unit tests'
        run: npm test -- --coverage

      - name: 'Check types'
        run: npm run check:types

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: 'Install dependencies'
        run: npm ci

      - name: 'Build web app artifacts'
        run: |
          npm run build

      - uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: dist

  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Reconfigure git to use HTTP authentication
        run: >
          git config --global url."https://github.com/".insteadOf ssh://git@github.com/

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Install E2E dependencies and browsers
        run: |
          cd e2e
          npm ci
          npx playwright install --with-deps

      - name: Start backend Redis services
        run: docker compose up -d
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

      - name: Start services
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          # Start api
          npm run start:api &
          # Start tracker
          npm run start:tracker &
          # Start frontend
          VITE_TRACKER_URL='ws://localhost:8000' npm run start &

          # Wait for services to be ready
          npx wait-on tcp:3000 tcp:3001 tcp:8000 -t 60000

      - name: Run E2E tests
        run: npm run e2e
